### PR TITLE
IWW Issue #23, October 13th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the October 13th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is October 12th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: Release Notes for Safari Technology Preview 114
url: https://webkit.org/blog/11300/release-notes-for-safari-technology-preview-114/
author: Jon Davis
content: WebGL2 is now on by default in Safari tech preview!

**Comment by TrevorFSmith** [comment]
title: LÖVR 0.14.0 Upgrades from WebVR to WebXR
url: https://twitter.com/bjornbytes/status/1315716348815659010
author: Bjorn ?
content: WebXR has better browser support, works with more controllers, and has newer features like hand tracking on the Quest.

**Comment by TrevorFSmith** [comment]
title: Using WebXR with Babylon.js
url: https://www.smashingmagazine.com/2020/10/using-webxr-with-babylonjs/
author: Preston So
content: In this overview of WebXR technologies and the Babylon.js framework, we’ll embark on a journey through the past, present, and future of mixed reality both on the web and on immersive headsets. We’ll inspect the underpinnings of WebXR and the most important aspects of the WebXR Device API before turning our attention to Babylon.js, a framework for building immersive applications in JavaScript for web, mobile, and headset. This tutorial is geared toward web and JavaScript developers who build web applications but are looking to dip their toes into immersive experiences.

**Comment by TrevorFSmith** [comment]
title: ROAR Retrospective
url: https://piesku.com/roar/
author: Piesku
authorLink: https://piesku.com/
content: A development log about, Roar, the only WebXR entry in the 2020 edition of js13kgames to not use an external rendering library like Three.js or Babylon.js

**Comment by TrevorFSmith** [comment]
title: Moving Physics Off the Main Thread
url: https://surma.dev/things/omt-for-three-xr/
author: Surma
content: "I recently became an owner of the Oculus Quest, and since the browser that comes with it has support for WebXR, I thought it only sensible to play around with that API. I looked at the Three.js examples and tried out the XR samples. Annoyingly, even the rather bare-bones Ballshooter was fun. However, I felt like it didn’t have enough balls. Time to start hacking!"
https://github.com/GoogleChromeLabs/comlink

**Comment by TrevorFSmith** [comment]
title: ZapBox Kickstarter
url: https://www.kickstarter.com/projects/all-newzapbox/all-new-zapbox-awesome-mixed-reality-for-40
author: Zappar
content: A new approach to affordable, mass market mixed reality hardware.

**Pull request merged**
