### PR TITLE
IWW Issue #29, December 1st 🙀 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the December 1st issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is November 30th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: xrpet.me, WebXR hand inputs demo
url: https://www.xrpet.me/
tweet url: https://twitter.com/Tojiro/status/1333218545262444544?s=20
github: https://github.com/toji/xr-critter
author: Brandon Jones
content: "Pet me!" is a WebXR experience where you pet a cat-thing.

**Comment by Yonet** [comment]
title: WebXR Scene Optimization
url: https://toji.github.io/webxr-scene-optimization/
author: Brandon Jones
content: A mini-tutorial covers some simple methods of optimizing 3D assets, especially for WebXR on mobile VR and AR devices, using free tools like Blender.

**Comment by TrevorFSmith** [comment]
title: New game: Sol Attrition
url: https://twitter.com/wwwtyro/status/1332809571249893380
author: Rye Terrell
authorLink: https://twitter.com/wwwtyro/

**Comment by TrevorFSmith** [comment]
title: Makepad
url: https://makepad.dev/
author: Rik Arends
authorLink: https://twitter.com/rikarends
content: A live-coding environment with VR support
https://github.com/makepad/makepad

**Comment by TrevorFSmith** [comment]
title: Immersive AR Emulation
url: https://github.com/adarosecannon/immersive-ar-emulation
author: Ada Rose Cannon
authorLink: https://mobile.twitter.com/Lady_Ada_King/
content: >
  <blockquote>
  This is a project designed to allow you to test your immersive-ar session in a VR headset it acts kind of like a polyfill, if immersive-ar is already supported then it does nothing. But if immersive-vr is supported and immersive-ar it will let it work by:

- In emulated immersive-ar draw a background scene behind your scene
- Modifying navigator.xr.isSessionSupported to override requests for immersive-ar to let it be allowed.
- Modifying navigator.xr.requestSession to return an immersive-vr session if an immersive-ar session is requested which has been modified such that:
- It supports requestHitTestSource by testing against the rendered background scene
- It modifies requestAnimationFrame so that each XRFrame returned has a replacement getHitTestResults
</blockquote>

**Pull request merged**
