### PR TITLE
IWW Issue #42 👍📔, March 16th 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the March 16th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: Virtual Modeling Kit is Faster, and has better render quality and improved physics!
url: https://twitter.com/fabiojcortes/status/1370389411964280836

(molecules)

**Comment by TrevorFSmith** [comment]
title: Some people within Google and Microsoft disagree about Australian news
url: https://www.theverge.com/platform/amp/2021/3/12/22327306/google-microsoft-attack-open-web-online-news-australia-laws

**Comment by Yonet** [comment]
title: <model-viewer> v1.6 is out now!
url:https://twitter.com/modelviewer/status/1370424932211912704?s=20
author:<model-viewer> 
content: This plugs a significant memory leak and works around an intermittent WebXR rendering bug, among other fixes, so the update is highly recommended.

**Comment by Yonet** [comment]
title: Transfer Your Poly Models with the New Poly-to-Sketchfab App
url: https://sketchfab.com/blogs/community/transfer-your-poly-models-with-the-new-poly-to-sketchfab-tool/
author: Abby Crowfard
content: As you may have seen, Google Poly, the 3D model sharing site from Google, will be shutting down on June 30, 2021 and will no longer allow new uploads to their site as of April 30, 2021. We have connected with the Google team to find a seamless solution to transfer models from Poly to Sketchfab and today we’re pleased to announce the launch of our Poly-to-Sketchfab app: polytosketchfab.com.

**Comment by TrevorFSmith** [comment]
title: 60+k in sales for an online performance
url: https://twitter.com/brendanAbradley/status/1371175211576434688

**Comment by jessicaoutlaw1** [comment]
title: Humans have almost no tolerance for algorithmic error: A workshop on overcoming algorithm aversion
url: https://extendedmind.mykajabi.com/overcoming-algorithm-aversion-webinar
author: Jessica Outlaw
content: For all emerging technologists working at the intersection of XR and AI, two behavioral scientists are hosting a free workshop on April 8th on why people trust other humans more than algorithmic models, even when the algorithm objectively outperforms the human.  Come learn 3 Principles of human centered algorithm design, strategies to overcome algorithm aversion, and more. Click [here ](https://extendedmind.mykajabi.com/overcoming-algorithm-aversion-webinar) for more details and to register.

**Pull request merged**
