### PR TITLE
IWW Issue #19, September 15th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the September 15th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith and Bob Fe
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is September 14th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: Facebook Connect Free AR/VR Event
url: https://www.facebookconnect.com/
author: Facebook Reality Labs
content: Join our biggest AR/VR conversation of the year.
Brought to you by Facebook Reality Labs. See the
current speakers today. Stream it on Facebook
Live on September 16 at 10 AM PT.

**Comment by mjelbart** [comment]
title: Designs for a Cooler Planet exhibition Costume in Augmented Reality
url: https://urscostume.glitch.me https://ursbeans.glitch.me 
author: Michael Jelbart
authorLink: https://www.tophatwombat.com 
content: In collaboration with costume designer, [Urs Dierker](https://www.ursdierker.com/), Michael Jelbart, Helsinki-based XR developer, created a cheery AR Business Card featuring shiny bean-like shapes gently spinning, and linking to the artist’s portfolio.
For the Helsinki Design Week, the team also translated a costume from exhibition Naturally Dramatic into an accessible WebAR experience. The sustainable textile and material design for stage and film costumes exhibition reached a wider audience despite the limited openings due to COVID 19. The photogrammetric model is displayed using [model-viewer](https://modelviewer.dev/) with a custom link for Chrome on iOS. Enjoy the experience!

**Comment by TrevorFSmith** [comment]
title: Aardvark Spatial Browser
url: https://medium.com/@joe_28841/aardvark-and-augmented-virtual-reality-7bf018e04b84
author: Joe Ludwig
authorLink: https://medium.com/@joe_28841
content: >
  Aardvark is an open-source browser that runs on Windows and can run over any SteamVR application on any SteamVR-compatible headset. Each gadget is essentially an off-screen browser “tab”. Gadgets can be bookmarked and reopened later and shared via URLs. They also be run on-demand when the user wants to use a gadget without the need to install anything. Deploying a new build is as simple as uploading to a web server. The gadgets themselves can be entirely client-side, or can contact back-end services using any network or streaming capabilities they could use in a desktop browser.

**Comment by TrevorFSmith** [comment]
title: Relatvty Open Sources their VR Headset
url: https://twitter.com/maxcoutte/status/1304008148282478592
author: Max Coutte and Gabriel Combe-Ounkham
authorLink: 
content: >
  "I’m Max Coutte and when my best friend Gabriel Combe and I were 15 years old we built our own VR headset because we couldn't afford to buy one. Relativty is not a consumer product. We made Relativty in my bedroom with a soldering iron and a 3D printer and we expect you to do the same."
  https://www.relativty.com/

**Pull request merged**
