### PR TITLE
IWW Issue #48 🤫, April 27th 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the April 27th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: glTF prep tool
url: https://twitter.com/lewy_blue/status/1384876828226056200

**Comment by jessicaoutlaw1** [comment]
title: Free workshop on 3 Strategies to Embed Ethics in Technology
url: https://extendedmind.mykajabi.com/3-key-strategies-free-event-bonus
author: Jessica Outlaw
content: Imagine if you had leadership tools to shape technology to be ethically aligned. This event is designed for technologists, designers, executives, and engineers in the immersive tech industry who want to learn more about applied ethics and behavioral science.

**Comment by Yonet** [comment]
title: MIT Reality Hack June 17-21, 2021
url:https://www.mitrealityhack.com/
content: Reality Hack is an annual community-run XR hackathon comprising thought leaders, brand mentors and creators, participants, students, and technology lovers, who come together and attend tech workshops, talks, discussions, fireside chats, collaborations, hacking, and more.Participants of various backgrounds and all skill levels attend from all over the world.

I was there as a mentor and gave a workshop. It was fun!

**Comment by Yonet** [comment]
title: OCULUS GAMING SHOWCASE: NEW TRAILERS, BEHIND-THE-SCENES FOOTAGE, AND MORE
url: https://www.oculus.com/blog/oculus-gaming-showcase-new-trailers-behind-the-scenes-footage-and-more/
content: With the launch of Oculus Quest 2 and the release of some awesome games like POPULATION: ONE, Star Wars: Tales from the Galaxy’s Edge, The Walking Dead: Saints & Sinners, Medal of Honor: Above and Beyond, and more, 2020 was a banner year for VR. And 2021 is shaping up to be jam-packed with similar momentum. 
author: oculus

**Comment by TrevorFSmith** [comment]
title: DAT.GUI in VR
url: https://twitter.com/mrdoob/status/1385184290867187715
author: Ricardo

**Comment by TrevorFSmith** [comment]
title: Imanol on WebXR in WebKit
url: https://twitter.com/MortimerGoro/status/1385267008711823364

**Comment by TrevorFSmith** [comment]
title: Secret Sky
url: https://stream.secretskyfest.com/

**Comment by TrevorFSmith** [comment]
title: ARBase Release
url: https://arbase.io/blogs/news-and-updates/beta-progress

**Comment by TrevorFSmith** [comment]
title: 8th Wall release
url: https://www.8thwall.com/blog/post/45786174106/introducing-release-16-8th-walls-world-class-ar-engine-for-the-web-just-got-even-more-powerful

**Pull request merged**
