### PR TITLE
IWW Issue #21, September 29th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the September 29th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is September 28th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: Supercharge your workflow with Template Assets!
url: https://blog.playcanvas.com/supercharge-your-workflow-with-template-assets/
author: Steven Yau 
content: The PlayCanvas team is very excited to announce the public release of new Templates feature! 🎉

**Comment by NikLever** [comment]
title: Learn to Create WebXR, AR and VR, experiences using Three.JS
url: https://www.udemy.com/course/learn-webxr/?couponCode=SEP20_SALE
author: Nik Lever
content: A Udemy course showing how easy it is to create WebXR apps using the popular Open Source WebGL library Three.JS. The course starts with an introduction to WebXR before going on to provide a Three.JS primer. Then we start to create some simple VR and AR examples. The course concludes with more complex examples, including an architectural walk-through, fun AR examples, VR gaming techniques and using VR for training.

**Comment by Yonet** [comment]
title: Introduction to WebXR Series
url: https://medium.com/youngsphere/1-introduction-to-webxr-53c293b4bfb5
author: Vivek Chandela
content: This is a series on using WebXR to build immersive content, starting from basic scene with AFrame, to hit-testing to DOM Overlay.

**Comment by TrevorFSmith** [comment]
title: KaiXR Launches
url: https://www.kaixr.com/
author: Kai M. Frazier
content: Today KaiXR launched a new accessible and inclusive platform for VR field trips with 4 school groups ranging from Harvard to South Central with roughly 1,000 end users.

**Pull request merged**
