### PR TITLE
IWW Issue #22, October 6th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the October 5th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is October 5th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: We added personal avatars to Mozilla Hubs and this is what happened
url: https://readyplayer.me/blog/we-added-personal-avatars-to-mozilla-hubs-and-this-is-what-happened
author: Timmu Tõke
content: Soon after COVID hit and made our team go fully remote, we quickly got tired of seeing each other's faces on video and decided to give Mozilla Hubs a try – so we could meet up in the same room, virtually.

**Comment by Yonet** [comment]
Title: three.js r.121 released
Url: https://twitter.com/threejs_org/status/1311254192238071808?s=20

**Comment by TrevorFSmith** [comment]
> Title: three.js r.121 released
> Url: https://twitter.com/threejs_org/status/1311254192238071808?s=20

I'm excited to see experimental WebGPU support.

**Comment by TrevorFSmith** [comment]
title: FrameVR releases Frame Academy
url: https://learn.framevr.io/academy
author: FrameVR
content: Six projects and a WebXR Workshop series for STEM educators.
New environments like Boring Island: https://www.framevr.io/boringisland

**Comment by TrevorFSmith** [comment]
title: js13kGames WebXR Winners
url: https://js13kgames.com/#winners
author: js13kGames
content: 
1st place: https://js13kgames.com/entries/exit
2nd place: https://js13kgames.com/entries/13kb-404
3rd place: https://js13kgames.com/entries/ned-snow

**Comment by TrevorFSmith** [comment]
title: Community Created WebXR Discord
url: 
author:
content:

Brian Peiris tweet: https://twitter.com/brianpeiris/status/1313148263038627840
invite link: https://t.co/2LgBjhAnhx

**Comment by TrevorFSmith** [comment]
title: Moon Rider creator reveals sticky usage numbers
url: https://twitter.com/dmarcos/status/1312868636797939717
author: Diego Marcos
content: "18 months after release more than 500 users spend longer than 15 mins everyday. All organic within the community."

**Pull request merged**
