### PR TITLE
IWW Issue #40, March 2nd 🌳 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the March 2nd issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Squareys** [comment]
As always, thanks for maintaining IWW!

```
title: Wonderland Engine is now free!
url: https://wonderlandengine.com/news/wonderland-engine-is-now-free/
author: Jonathan Hale
content: With its switch to a royalty based license model, the WebXR focused development plaform is now free to use for everyone.
```

**Comment by TrevorFSmith** [comment]
title: three-elements is released
url: https://hmans.co/posts/2021-02-02-three-elements-0-3/

**Comment by TrevorFSmith** [comment]
title: Lidar scan onto the web
url: https://albn.medium.com/3d-scanning-with-the-iphone-lidar-8cbd723fc9ab
author: Alban Denoyel

**Comment by TrevorFSmith** [comment]
url: https://github.com/aelatgt/three-web-layer
title: three-web-layer
Uses https://html2canvas.hertzen.com/

**Comment by TrevorFSmith** [comment]
url: https://mobile.twitter.com/dmarcos/status/1316040052179300352
title: WebXR Layer experiment with OTOY stereo cubemaps

**Comment by TrevorFSmith** [comment]
title: Wooglies
url: https://mobile.twitter.com/JureTriglav/status/1365856644563947521

**Comment by TrevorFSmith** [comment]
title: A-frame Vatiste Toolkit ships PhysX
url: https://vartiste.xyz/docs.html#physx

**Pull request merged**
