### PR TITLE
IWW Issue #32, January 5th 🏂 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the January 5th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: Emulating webxr hardware with computer vision!
url: https://twitter.com/MIDIBlocks/status/1342289627730780160
author: Oz Ramos
content: Mozilla WebXR Emulator Extension to emulate the hardware hands free, w/o any further config! Emulation of hand controllers soon.

**Comment by Yonet** [comment]
title: WebXR input profiles stats
url: https://twitter.com/Tojiro/status/1343079273662279681
author: Brandon Jones
content: So according to the WebXR input profiles stats a whole bunch of you got Quest 2s for Christmas (and tried some WebXR content!)

**Comment by TrevorFSmith** [comment]
title: >
  Reality Check: Looking Back at Augmented Reality in 2020
author: Tom Emrich
content: Tom evaluates his predictions about AR in 2020.

**Comment by TrevorFSmith** [comment]
title: Desktop Vision
url: https://desktop.vision/
content: A remote desktop tool that works in both flat and XR display modes

**Comment by TrevorFSmith** [comment]
title: SomniumSpace moves onto the Web
url: https://twitter.com/SomniumSpace/status/1346152903833223168
content: Somnium Space is an "Open, Social, Virtual Reality world. A world with its own economy and its own currency. A VR world with its own Marketplace, Games, Social experiences and Virtual Land ownership." They have a native app but just released a beta of a fully web based XR app.

**Pull request merged**
