### PR TITLE
 IWW Issue #34, January 19th 💪 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the January 19th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Maksims** [comment]
title: WebXR integrations into PlayCanvas: Depth Sensing, Image Tracking, DOM Overlays
url: https://playcanvas.com/
author: Maksims Mihejevs (@mrmaxm)
content: With new PlayCanvas engine update [1.38.0](https://github.com/playcanvas/engine/releases/tag/v1.38.0), new integrations into engine been deployed for everyone. Those include: [Depth Sensing](https://github.com/playcanvas/engine/pull/2561) with GPU and CPU paths, which allows to get better distance sense in AR session. [Image Tracking](https://github.com/playcanvas/engine/pull/2574) - allows to actively track images in real world during AR session. And [DOM Overlays](https://github.com/playcanvas/engine/pull/2614) - simple way to use HTML + CSS with AR session. Also Input Sources now can be [squeezed](https://github.com/playcanvas/engine/pull/2632). All WebXR integrations in PlayCanvas, make developer lives easier and benefit from engine features.

**Comment by TrevorFSmith** [comment]
title: WebXR Meetup with Ada Rose Canon
url: https://www.meetup.com/Web-VR/events/275691745/
content: Join us as we invite Ada Rose Cannon, Developer Advocate/Staff Engineer at Samsung & Co-chair of the W3C Immersive Web Working Group and Community Group, to share with us the latest and greatest with the WebXR Device API and more! Register for the webinar below.

**Comment by TrevorFSmith** [comment]
title: ShaderWorlds Collaborative XR Spaces
url: https://shaderworlds.com/
url: https://github.com/jure/shaderworlds
content: "A collection of open source VR-enabled shader worlds"

**Comment by TrevorFSmith** [comment]
title: CineShader
url: https://cineshader.com/
content: "A real-time 3D shader visualiser. It leverages the Shadertoy.com API to bring thousands of existing shader artworks into a cinematic 3D environment."

**Pull request merged**
