### PR TITLE
IWW Issue #30, December 8th 🍰 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the December 8th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is December 7th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by bialpio** [comment]
title: Depth Sensing API Origin Trial in Chrome for Android 87 & 88
url: https://developers.chrome.com/origintrials/#/view_trial/1934296039955628033
author: Piotr Bialecki
content: Calling all developers! Depth Sensing API Origin Trial will be active in Chrome for Android 87-88 - if you'd like to take it for a spin, register [here](https://developers.chrome.com/origintrials/#/register_trial/1934296039955628033) to obtain the Origin Trial token that can be used on your page. To learn about the API, read the [explainer](https://github.com/immersive-web/depth-sensing/blob/main/explainer.md) & take a look at the 2 [sample](https://immersive-web.github.io/webxr-samples/proposals/phone-ar-depth.html) [pages](https://immersive-web.github.io/webxr-samples/proposals/phone-ar-depth-gpu.html). Don't forget to file feedback about the API on [GitHub](https://github.com/immersive-web/depth-sensing/issues)! More information about what Chrome's Origin Trial is can be found [here](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md).

**Comment by TrevorFSmith** [comment]
@bialpio Hey, thanks for the links. However, I covered the depth sensing origin trial in [issue 28](https://immersivewebweekly.com/issues/028/)!

**Comment by TrevorFSmith** [comment]
title: Spatial Chat On The Web
url: https://www.wired.com/story/zoom-parties-proximity-chat/
author: Gretchen McCulloch
Also includes a list of 30 proximity chat sites:
https://docs.google.com/spreadsheets/d/1FgynDnnrrllZZUa42XcKSfD68G5VAMZsLkARXHtgHOM/

**Comment by TrevorFSmith** [comment]
title: MoleculAR Web
url: https://molecularweb.epfl.ch/
content:
Found in this thread: https://twitter.com/fabiojcortes/status/1335918809828438018

**Comment by TrevorFSmith** [comment]
title: New Material Capabilities for glTF
url: https://www.khronos.org/news/press/khronos-releases-wave-of-new-gltf-pbr-3d-material-capabilities
content: Adds clear coat, transmission and sheen

**Comment by TrevorFSmith** [comment]
title: Talk: The future of the web in an XR world
url: https://githubuniverse.com/The-future-of-the-web-in-an-XR-world/
author: Jaume Sánchez Elias
content: On December 10, 10:30 AM PST at GitHub Universe 2020
announcement: https://twitter.com/thespite/status/1335677762724651009

**Comment by TrevorFSmith** [comment]
title: Ex-Hubs Manager Announces Jel
url: https://gfodor.medium.com/introducing-jel-the-un-zoom-320d3dcfd8f6
author: Greg Fodor

**Comment by TrevorFSmith** [comment]
title: Google Poly is Shutting down
url: https://support.google.com/poly/answer/10192635

**Pull request merged**
