### PR TITLE
IWW Issue #52, May 25th 🙀 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the May 25th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: First public working drafts of WebGPU and its shader language
url: https://www.w3.org/blog/news/archives/9059

**Comment by TrevorFSmith** [comment]
title: Market for Three
url: https://twitter.com/0xca0a/status/1394697847556149250

**Comment by Yonet** [comment]
title: Environment-Aware WebXR Augmented Reality
url: https://github.com/tentone/ar-occlusion
author: José Ferrão
content: Web-based framework for environment-aware rendering and interaction in augmented reality based on WebXR using three.js

**Comment by Yonet** [comment]
title: Google I/O WebXR Codelabs
url: https://codelabs.developers.google.com/ar-with-webxr#0
author: Dereck Bridie, Jordan Santell
content: Build an augmented reality (AR) app using the WebXR Device API with this step by step tutorial from Google Codelabs.

**Comment by TrevorFSmith** [comment]
title: New layers samples
url: https://twitter.com/Tojiro/status/1395420677864255491

**Pull request merged**
