### PR TITLE
IWW Issue #14, August 11th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the August 11th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith and Bob Fe (the people or organization who created whatever is at the link)
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is August 10th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: Firefox Reality PC Preview
url: https://blog.mozvr.com/introducing-firefox-reality-pc-preview/
author: Thomas Moore
summary: Previously, Firefox Reality was on all-in-one headsets like Facebook's Quest and Pico's Neo. This release brings the XR-native browser to PCs so that you can browse flat and XR content without leaving your tethered headset.

**Comment by Yonet** [comment]
title: Play Canvas Engine v1.33.0 is out! 
url: https://github.com/playcanvas/engine/releases/tag/v1.33.0
content: Play Canvas Engine adds WebXR Tracked Hands API and example, courtesy of @Maksims

Not really an article but newsworthy.

**Comment by TrevorFSmith** [comment]
title: A New Hand Input Library: Handy
url: https://twitter.com/stew_rtsmith/status/1292883258812792833
url: https://github.com/stewdio/handy.js
author: Steward Smith
summary: Handy makes defining and using custom hand shapes in WebXR a snap. Just name your hand shape (eg. “pinch”) and write a function that defines the shape. Handy will create and update convenience booleans that you can query in your update loop, and it will create custom events that you can listen for.

**Comment by TrevorFSmith** [comment]
title: cARs on the web
url: https://medium.com/8th-wall/a-week-in-webar-automotive-edition-a219688a1e62
author: 8th Wall
summary: Maserati, Porsche, Volvo, MINI Cooper and Toyota hit the web with XR ad campaigns.

**Comment by TrevorFSmith** [comment]
title: ensmallen your big art for the web
url: https://rapidcompact.com/
author: Rapid Compact
summary: Khronos just announced that they're supporting the latest glTF as one of the targets for their tool that converts massive CAD files or scans into immersive web-friendly-sized assets.

**Comment by TrevorFSmith** [comment]
title: Tour the National Museum of Computing at Bletchley Park
url: https://my.matterport.com/show/?m=pq6v8gMmxMw
url: https://www.tnmoc.org/news-releases/2020/8/7/step-through-the-screen-and-into-tnmoc-this-summer

**Comment by TrevorFSmith** [comment]
title: Write your first VR web app with React
url: https://blog.dubenko.dev/react-xr/
author: Oleksandr Dubenko
summary: "This is a tutorial for those who have a VR device on your hands and want to try building something for VR or for those who are just curious how VR with React works. For this post, I’m going to assume that you’re only familiar with React and never tried any 3D or VR libraries before."

**Comment by TrevorFSmith** [comment]
title: Fly Around Class Video Games
url: https://noclip.website/
url: https://mobile.twitter.com/ben_rainwolf/status/1289783854094381057
author: Jasper (https://twitter.com/JasperRLZ)
summary: A web site that brings many classic video game levels to the web has added WebXR support.

**Pull request merged**
