### PR TITLE
IWW Issue #25, 💀 October 27th 💀 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the October 27th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is October 26th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: FRAME lets you have 30 people inside a FRAME at once
link:https://twitter.com/frame_vr/status/1318938970701455365?s=20
author: frame.io
content: Last update to FRAME lets you have 30 people inside a FRAME at once, but we aren't stopping there. We can't wait to show you what's in store for our cross-platform immersive meeting tool.

**Comment by Yonet** [comment]
title: How An Indie Festival Is Fostering A New Kind of International Cinema In The Pandemic
url:https://medium.com/@kmshotline/how-an-indie-festival-is-fostering-a-new-kind-of-international-cinema-in-the-pandemic-55fbf3e35f92
author: Keram M-S
content: Shared reasons why WebXR Immersive Media & it's content creators are doing an important thing.

**Comment by Yonet** [comment]
title: VRIA: A Web-based Framework for Creating Immersive Analytics Experiences
url: https://twitter.com/ieeevis/status/1318980369761271808?s=20
paper url: https://ieeexplore.ieee.org/document/8954824
authors: Peter William Scott Butcher, Nigel W. John, Panagiotis D. Ritsos
content: Build Web-based immersive analytics experiences in #XR, accessible in your browser, viewable on a variety of displays, with the open-source VRIA framework!

**Comment by TrevorFSmith** [comment]
title: First Working Draft of the Hands API
url: https://www.w3.org/blog/news/archives/8734

**Pull request merged**
