### PR TITLE
IWW Issue #15, August 18th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the August 18th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith and Bob Fe (the people or organization who created whatever is at the link)
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is August 17th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
Title: Virtual Tours of the Museum of the Fossilized Internet
Url: https://blog.mozilla.org/blog/2020/08/06/virtual-tours-of-the-museum-of-the-fossilized-internet/
Author: Cathleen Berger
Content: In March 2020, Michelle Thorne and I announced office tours of the Museum of the Fossilized Internet as part of our new Sustainability program. Then the pandemic hit, and we teamed up with the Mozilla Mixed Reality team to make it more accessible while also demonstrating the capabilities of social VR with Hubs.

**Comment by TrevorFSmith** [comment]
Note: I mistakenly made the subject of last week's issue 15 when it was in fact 14.
Sorry for the confusion.

**Comment by TrevorFSmith** [comment]
title: Mozilla is Changing
url: https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/
author: Mitchell Baker
content: Layoffs, reorg, and more product-driven work

**Comment by Yonet** [comment]
title:Nreal’s augmented reality glasses are shipping this month in Korea
url: https://www.theverge.com/2020/8/10/21362407/nreal-light-ar-glasses-lg-uplus-samsung-galaxy-note-retail-launch-availability-price
author:
content: The Nreal Light mixed reality glasses are shipping in Korea alongside Samsung’s newly announced Galaxy Note 20. t’s promising to support Chrome, Facebook, and Instagram, among other apps, at launch.

**Comment by TrevorFSmith** [comment]
Additional article for @Yonet's news ☝
 
title: Nreal Light AR glasses launch with VR lenses
url: https://venturebeat.com/2020/08/10/nreal-light-ar-glasses-add-vr-lenses-launch-august-21-in-south-korea/
author: Jeremy Horwitz
authorLink: https://twitter.com/horwitz

**Comment by TrevorFSmith** [comment]
title: Sketchfab and Run The Jewels invite an immersive web remix
url: https://sketchfab.com/blogs/RTJ4D/
author: Sketchfab
content: The immersive web has progressed far enough that team-ups like Sketchfab and the band Run The Jewels make business sense. Artists are invited to remix 3D assets related to a new album and then repost them on Sketchfab where they can be viewed in AR and VR.

**Comment by TrevorFSmith** [comment]
title: Ninth annual js13kgames adds a WebXR challenge
url: https://js13kgames.com/webxr
url: https://medium.com/js13kgames/js13kgames-2020-has-started-c7e003292613
author: Andrzej Mazur
authorLink: https://end3r.com/

**Pull request merged**
