### PR TITLE
IWW Issue #35, January 26th 🤷🏻‍♀️ 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the January 26th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Yonet** [comment]
title: HandsFree.JS release
url: https://twitter.com/MIDIBlocks/status/1351423611857326080
author: Alice Smith
content: The new "Palm Pointers" and "Pinch Scroll" plugins are ready!
This release includes:
- One pointer per hand (up to 4 hands)
- Ability to scroll any area in any direction
- New boilerplate

**Comment by AdaRoseCannon** [comment]
title: Making an AR Game
url: https://medium.com/samsung-internet-dev/making-an-ar-game-with-aframe-529e03ae90cb
author: Ada Rose Cannon
content: This is an in-depth article on using AFRAME and WebXR to build an Augmented Reality game.

**Comment by TrevorFSmith** [comment]
title: >
  GamesBeat: Driving Game Growth & Into the Metaverse
url: https://events.venturebeat.com/gamesbeat-into-the-metaverse/gbmetaverseagenda/
author: VentureBeat
content: A single-track, free, and fully online conference on January 26th through 28th with the topic of "the metaverse".

 It would be great to have immersive web folks in the chat to shill for web solutions.

**Comment by TrevorFSmith** [comment]
title: Aardvark looking for gadget creators
Repo: https://github.com/aardvarkxr/aardvark
Article: https://www.roadtovr.com/aardvark-ar-in-vr-gadgets-joe-ludwig/amp/
Steam early access: https://store.steampowered.com/app/1466430/Aardvark/

**Pull request merged**
