### PR TITLE
IWW Issue #38, Feb 16th ⏰ 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the February 16th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by VirtualityXR** [comment]
title: Defining the Next Normal for Immersive Concert Experiences
url: https://www.vrfocus.com/2021/02/defining-the-next-normal-for-immersive-concert-experiences/
author: Mark Rickard
content: Unpacking the recent past and near-future of the virtual concert landscape, plus the impact and perceived staying-power for each of the disparate immersive platforms

**Comment by TrevorFSmith** [comment]
title: IEEE Global Initiative on Ethics of Extended Reality
url: https://standards.ieee.org/industry-connections/ethics-extended-reality.html
content: >
  "The goal of this Industry Connections activity is to continue and proliferate the existing efforts of The IEEE Standards Association focused on the ethical issues related to XR as outlined in the Extended Reality chapter of Ethically Aligned Design while inviting Working Group members from the multiple standards Working Groups focused on augmented and virtual reality and the spatial web and additional subject matter experts from industry and policy to create white papers, workshops, and PARs related to this work to ensure these technologies move from perilous to purposeful."
  Outlaw's tweet: https://twitter.com/theextendedmind/status/1359654418350710786

**Comment by NikLever** [comment]
title: Add AR to an online shop using WebXR and ThreeJS
url: http://bit.ly/ar-shop-article
author: Nik Lever
content: AR is the perfect solution for viewing a product in your own home. In this article we look at using WebXR and ThreeJS to add AR experiences to an online shop.

**Comment by TrevorFSmith** [comment]
title: FIVARS festival of international XR stories
url: https://fivars.net/
content: >
  It runs from Feb 19th to March 2nd
  Tickets are available now: $25-$42 CAD

**Comment by Yonet** [comment]
url: https://www.brendanabradley.com/futurestages
video: https://youtu.be/K7MqCO72hEE
content: Brendan Bradley has designed a virtual performance experience that is optimized and customizable for Mozilla Hubs which allows access via the same URL by almost any device: VR headset, personal computer or mobile device. 
author: Brendan Bradley

**Comment by TrevorFSmith** [comment]
title: IEEE International symposium on mixed and augmented reality
url: http://www.ismar21.org/
content: >
  Bari, Italy
  October 4 to 8
  Abstract Deadline: 7th March

**Pull request merged**
