### PR TITLE
IWW Issue #47 😸, April 20th 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the April 20th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by jdwilt** [comment]
title: Virtual Frederick Visitor Center
url: https://braincavexr.com/fvc.html
author: BraincaveXR
content: The virtual Frederick Visitor Center includes custom 3D environments and interactive exhibits that visitors can explore with Oculus Quest VR headsets or PC web browsers. The BraincaveXR platform incorporates ThreeJS and WebGL with its own robust scripting language to produce spatially immersive experiences.

**Comment by TrevorFSmith** [comment]
title: NVIDIA's metaverse plans
url: https://venturebeat.com/2021/04/12/nvidia-reveals-omniverse-enterprise-for-simulating-products-and-worlds/

**Comment by TrevorFSmith** [comment]
title: Hands go live
url: https://twitter.com/rcabanier/status/1383216671725264900

**Comment by TrevorFSmith** [comment]
title: Packaging Three.js projects as eco-NFTs
url: https://mobile.twitter.com/marioecg/status/1384195565857107971

**Comment by Squareys** [comment]
title: Build a WebXR Climbing Game for Quest
url: https://www.youtube.com/watch?v=weLqXfm_pyo&list=PL6kSJyWbCsqRyq9HAhUBOu5jdQNXe4scc
author: Wonderland Engine
content: Full video course on implementing a simple climbing game in Wonderland Engine.

**Pull request merged**
