### PR TITLE
IWW Issue #13, August 4th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the August 4th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith and Bob Fe (the people or organization who created whatever is at the link)
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is August 3rd) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Maksims** [comment]
title: PlayCanvas adds support for WebXR Hand Input API
url: https://github.com/playcanvas/engine/pull/2316
author: PlayCanvas team and Maksims Mihejevs (PR)
content: With recent release of experimental access to Hands Input in Oculus Quest Browser, hands tracking became available for developers. Adding API and support for such API, provides easy access for developers to bring hands to their XR apps.

**Comment by TrevorFSmith** [comment]
title: SharedArrayBuffers are back in Firefox!
url: https://hacks.mozilla.org/2020/07/firefox-79/
author: Florian Scholz, Chris Mills, Harald Kirschner
summary: This opens up multi-threaded WebAssembly and opens the door for engines like Unity to export efficient apps to the web.

https://hacks.mozilla.org/2020/07/safely-reviving-shared-memory/

**Comment by TrevorFSmith** [comment]
title: Microsoft joins the Blender Development Fund
link: https://www.blender.org/press/microsoft-joins-the-blender-development-fund/
author: Ton Roosendaal
summary: Blender picks up speed and support with Microsoft joining at the level that funds a Blender developer for 6 months each year. Other corporate sponsors at this level include Intel and Ubisoft.

**Comment by TrevorFSmith** [comment]
title: Recreating Journalistic Scenes in 3D
link: https://rd.nytimes.com/projects/reconstructing-journalistic-scenes-in-3d
author: NY Times R & D
summary: The researchers are experimenting with including full 3D scenes in news articles, opening the way for WebXR experiences.

**Comment by AdaRoseCannon** [comment]
Title: Add augmented reality features to your website using WebXR and @aframevr  
link: https://developer.samsung.com/internet/blog/en-us/2020/07/16/adding-augmented-reality-to-your-websites  
author: Ada Rose Cannon  
summary: This article introduces the augmented reality features of WebXR and has an AFrame project you can remix to build your own AR web site.

**Comment by TrevorFSmith** [comment]
title: WebGL2 turned on by default in upcoming Safari preview
link: https://mobile.twitter.com/grorgwork/status/1289679221313290240
author: Dean Jackson (Apple)

**Comment by TrevorFSmith** [comment]
title: React for XR Gaining Momentum
link: https://github.com/react-spring/react-three-fiber
link: https://github.com/react-spring/react-xr
link: https://twitter.com/dubenko_
link: https://twitter.com/kentbye/status/1290302731916161025

**Pull request merged**
