### PR TITLE
IWW Issue #31, December 15th ☃️ 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the December 15th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
The first commit in this PR notes "issue 30" but is actually issue 31. 🤷🏻‍♀️

**Comment by Yonet** [comment]
title: ART+TECH FESTIVAL 2020『 JOYNT 』
url: https://codame.com/events/art-tech-festival-2020-joynt
content: At the 10th annual ART+TECH Festival you can attend to AR and VR workshops like "Make AR Holiday Cards" and "Build VR with JS", as well as online art galleries and events.

**Comment by TrevorFSmith** [comment]
title: A new in-XR editor arrives
url: https://twitter.com/dannyaroslavski/status/1338030154900066305
author: Danny Yaroslavski
authorLink: https://twitter.com/dannyaroslavski

**Comment by TrevorFSmith** [comment]
title: Facebook is under investigation by German officials over its virtual reality headset, the Oculus Quest.
url: https://www.bbc.com/news/technology-55274547
author: BBC News
content: >
  <blockquote>The Oculus Quest 2 requires a Facebook account to work, something widely criticised by reviewers and VR fans. Germany's competition authority now says that requirement could be an abuse of Facebook's dominant market position.</blockqoute>
  Facebook previously [stopped sales of the Quest 2](https://www.bbc.com/news/technology-54014217) in Germany on September 3rd because of regulations that prevent merging data from its otherwise seperate services.

**Comment by TrevorFSmith** [comment]
title: Immersive Hopalong Orbits Visualizer
url: https://twitter.com/mrdoob/status/1337068939776581632
author:
content: > Experience: https://hopalongvr.glitch.me/

**Comment by TrevorFSmith** [comment]
title: TAG Reviews Layers and Hand Input
url:
content:
  Meeting minutes: https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/12-07-minutes.md
  Layers issue: https://github.com/w3ctag/design-reviews/issues/528
  Hand input issue: https://github.com/w3ctag/design-reviews/issues/568

**Pull request merged**
