### PR TITLE
IWW Issue #27, November 17th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the November 17th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is November 16th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: Create WebXR Voxels
url: https://www.youtube.com/watch?v=rDMLVdFtnYo&feature=youtu.be
author: Daniel Esteban
authorLink: https://twitter.com/DaniGatunes/
content: >
  https://twitter.com/DaniGatunes/status/1326146950320824320

**Comment by TrevorFSmith** [comment]
title: Oculus Go Wasn't Designed For Black Hair
url: https://twitter.com/ozm/status/1326568694869336065
author: Arwa Michelle Mboya
content: One designer's approach to widening VR's reach.

**Comment by Yonet** [comment]
> title: Oculus Go Wasn't Designed For Black Hair
> url: https://twitter.com/ozm/status/1326568694869336065
> author: Arwa Michelle Mboya
> content: One designer's approach to widening VR's reach.

As far as I know there are 0 headsets that is designed for black hair, unless you count Google Cardboard. The recommended design doesn't work for Afros. I've been asked this few times. Great article never the less.

**Comment by Yonet** [comment]
title: Babylon.js 4.2: Simplicity Reimagined
url:https://babylonjs.medium.com/babylon-js-4-2-simplicity-reimagined-965f88d0fad
author: Babylon.js
content: The latest evolution of the Babylon Platform, the amazingly simple Babylon.js 4.2 has new tooling as well as WebXR hand interaction module.

**Comment by TrevorFSmith** [comment]
title: AIGA design has a Hubs space for their 2020 design show
url: https://twitter.com/kentbye/status/1327380861658951680
author: Kent Bye (need to track down the space creators, too)

**Pull request merged**
