### PR TITLE
IWW Issue #12, July 28th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the July 28th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith and Bob Fe (the people or organization who created whatever is at the link)
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is July 27th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: <model-viewer> 1.0.0 release with AR and DOM overlay support via WebXR
url: https://modelviewer.dev/examples/webxr.html?mc_cid=6b5b70eeee&mc_eid=cabec33f49
author: Google
content: This release uses the experimental AR and DOM overlay specs in Chrome 83+

https://www.khronos.org/blog/view-a-gltf-model-in-ar-on-android-without-leaving-your-browser?mc_cid=6b5b70eeee&mc_eid=cabec33f49

**Comment by cabanier** [comment]
title: Oculus browser 10.2 is released with support for WebXR Layers and Hands tracking
url: https://twitter.com/jacobrossi/status/1285650075197124608
author: Oculus facebook
content: This release uses the experimental Layers and Hands specs:

https://immersive-web.github.io/layers/
https://github.com/immersive-web/webxr-hands-input/blob/master/explainer.md

**Comment by TrevorFSmith** [comment]
title: Statue of Liberty Virtual Tour
link: https://www.nps.gov/hdp/exhibits/stli/stli_tour.html?vr  (remove ?vr for flat version)
author: US National Park Service
content: A tour of 360 photos from the national monument that works in flat and immersive displays.

Does this work with WebXR or polyfill? Need to test.

**Comment by TrevorFSmith** [comment]
title: Cryptovoxels Grid Server is Live
link: https://twitter.com/cryptovoxels/status/1285412304079609856
author: Ben Nolan
content: What started as a friends-only experiment in 2018 to use the blockchain for digital space ownership has slowly grown and evolved into a multi-user immersive web space with user-contributed scripting. 

Docs are here: https://wiki.cryptovoxels.com/en/Scripting/TheGrid

**Comment by TrevorFSmith** [comment]
title: New working draft of WebXR
link: https://www.w3.org/TR/2020/WD-webxr-20200724/
author: IWWG
content: Publication of this draft is one of the final steps before the WebXR Device API becomes a standard! It includes changes based on feedback from the W3C Technical Advisory Board, the community, as well as lessons from early deployments in existing browsers.

**Pull request merged**
