### PR TITLE
IWW Issue 011: July 21st 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the July 21st issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

This is the first issue of the reboot so let's make it a good one!

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

To submit a link comment below using this template:

	Link: https://example.com/
	Authors: Alice Smith and Bob Fe (the people or organization who created whatever is at the link)
	Summary: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is July 20th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
WebGLStudio Hands On
Link: https://www.gamefromscratch.com/post/2020/06/18/WebGLStudio-Hands-On.aspx
Authors: GamesFromScratch.com
Summary: A video demonstration and review of an MIT licensed, in-browser scene editor for WebGL. The technology is broken up into reusable components (scene, graph editor, GL toolkit, ect) so it isn't hard to see how this could be repurposed for in-headset WebXR editing.

**Comment by TrevorFSmith** [comment]
Descend into the Elaborately Decorated Tomb of Pharaoh Ramesses VI Through This 3D Virtual Tour
Link: https://www.thisiscolossal.com/2020/07/ramesses-vi-tomb-virtual-tour/
Authors: Grace Ebert @ Colossal
Summary: Using Matterport they created a web-based tour

**Comment by TrevorFSmith** [comment]
Magic Leap Hires Top Microsoft Executive as C.E.O.
Link: https://www.nytimes.com/2020/07/07/technology/peggy-johnson-magic-leap-ceo.html
Authors: Erin Griffith and Karen Weise @ NYTimes
Summary: Immersive web browser and hardware developer, Magic Leap, has replaced Rony Abovitz with Peggy Johnson, formerly of Qualcomm and Microsoft.

**Comment by TrevorFSmith** [comment]
Link: https://skfb.ly/6TAxn
Authors: M.C. Escher and hinxlinx @ Sketchfab
Summary: Sketchfab user hinxlinx has recreated M.C. Escher's "Self-portrait in Spherical Mirror" for XR. I can't help but wonder if we could replace the reflection of M.C. Escher with the digital body of the user in WebXR.

**Comment by TrevorFSmith** [comment]
Virtual Beings Summit
Link: https://www.virtual-beings-summit.com/
Summary: An online conference in which all of the people on stage (most of whom are human) are wearing digital bodies.

**Comment by TrevorFSmith** [comment]
OpenCV/OpenVINO 
Link: https://www.kickstarter.com/projects/opencv/opencv-ai-kit
Summary: Kickstarter for "an MIT-licensed open source software and Myriad X-based hardware solution for computer vision." that might be usable for open immersive web headsets like the Northstar.

**Comment by Yonet** [comment]
The Brendan Bradley Future Stages
Link: https://www.brendanabradley.com/futurestages
Author: Brendan Bradley
Summary: Brendan Bradley has designed a virtual performance experience that is optimized and customizable for Mozilla Hubs and can be accessed using the same URL by almost any device: VR headset, personal computer or mobile device.

**Comment by Yonet** [comment]
Augmented Reality Measure App with WebXR and Three.js
Link: https://medium.com/@annika.wollschlaeger/augmented-reality-measure-with-webxr-and-three-js-a0c8355eb91a
Author: Annika Wollschläger
Summary: How to build a Measure app (like the ones available from Apple and Google) with WebXR and Three.js

**Comment by Yonet** [comment]
Case study: Moving a Three.js-based WebXR app off-main-thread
Link: https://surma.dev/things/omt-for-three-xr/
Author: Surma
Summary: Keeping the frame rate stable is vital for virtual reality applications. Off-main-thread architecture can help ensure that the frames keep shipping.

**Comment by Yonet** [comment]
This week in Servo
Link: https://blog.servo.org/2020/07/13/twis-132/
Summary: Last week was a busy one - we improved compatibility with Unity WebXR; fixed panics (Face screaming in fear) in canvas and WebAudio code; added some new media support; fixed a Windows websocket bug; and 360 immersive web recording is looking good!

**Comment by Yonet** [comment]
Oxford Digital Labs XRoom
Link: https://oxfordigitalab.com/xroom
Summary: OxforDigitaLab now has an Interaction Lab: A cross-platform WebXR demo for mobile VR, Oculus Quest and desktop.

**Comment by Yonet** [comment]
Veative Releases Entire STEM Library in a WebXR Format
Link: https://www.veative.com/blog/news/veative-releases-entire-stem-library-in-a-webxr-format/
Summary: In a response to the needs of teachers worldwide during this COVID-19 pandemic, Veative Labs has converted its entire STEM library of over 540 interactive, curriculum-aligned modules for the VR into a browser compatible WebXR version, ensuring that students and teachers everywhere have access to this world-leading library, regardless of location.

**Comment by TrevorFSmith** [comment]
Link: https://www.collabora.com/news-and-blog/news-and-events/lighthouse-positional-tracking-in-monado-with-libsurvive.html
Authors: Christoph Haag at Collabora
Summary: A fully open source software stack for VR is coming together at Collabora which will provide new hardware manufacturers with a better starting point for innovative products. It will also allow businesses to explore new software development and deployment strategies outside of the app stores, including use by the immersive web.

**Comment by jsantell** [comment]
Pushed my intro blurb and updated @TrevorFSmith's reference in links to Trevor Flowers (007 has another reference for you that I updated, change at your preference!)

**Comment by TrevorFSmith** [comment]
I manually merged this branch into master so I'm going to manually close this PR without merging a second time.

**Pull request closed without merging**
