### PR TITLE
IWW Issue #39, Feb 23rd 🦋 2021

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the February 23rd issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning around 10am Pacific time.

Trevor will edit each issue on the Monday before publication so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by Squareys** [comment]
Here's a link proposal:

```
title: Wonderland Engine 0.8.0 released
url: https://wonderlandengine.com/news/release-0.8.0/
author: Jonathan Hale
content: The latest version of the WebXR focused development platform now features Physics, Bloom, experimental WebAssembly SIMD support and a ton of workflow improvements.
```

Thanks for maintaining IWW!

**Comment by TrevorFSmith** [comment]
Title: Silk Brush is Tilt Brush in WebXR
Url: https://msub2.github.io/silk-brush/
Also, https://www.roadtovr.com/tilt-brush-webxr-google/

**Comment by TrevorFSmith** [comment]
title: WebRTC in the new Lumin update
url: https://www.magicleap.com/en-us/news/product-updates/lumin-os-0-98-20-and-lumin-sdk-0-25

**Comment by TrevorFSmith** [comment]
title: Chrome and Safari Teams Announce Intent
url: https://webkit.org/status/#specification-webxr
url: https://groups.google.com/a/chromium.org/g/blink-dev/c/v4fneq7tgDA/m/utkwOcjuAwAJ

**Pull request merged**
