### PR TITLE
IWW Issue #24, October 20th 2020

### PR DESCRIPTION
**Pull request by TrevorFSmith**
This pull request is for gathering links for the October 20th issue of the [Immersive Web Weekly](https://immersivewebweekly.com/) newsletter for the W3C Immersive Web Community Group.

If you have a link to a news article, event, artwork, or project that is directly related to the immersive web then we welcome your help!

### To submit a link comment below using this template:

	title: Example title of link
	url: https://example.com/
	author: Alice Smith
	content: A short description of what is at the link and why it's related to the immersive web

Please keep in mind that comments here and all submitted links are public!

We keep each issue pretty short so we won't immediately use every submission but we keep track of them all and they may appear in a later issue.

## Deadline
IWW goes out each Tuesday morning Pacific time.

Trevor will edit each issue on the Monday before (in this case that Monday is October 19th) so submissions after that will roll over for use in future issues.  

If you need editorial support then email @TrevorFSmith: trevor@transmutable.com

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
title: Wonderland Engine v0.7.1 ships
url: https://wonderlandengine.com/
author: Wonderland Engine team
content: In addition to releasing pricing, the team just shipped a major update to their WebAssembly-based rendering engine and experience editor.

**Comment by Yonet** [comment]
title: New WebXR Discord server
url: https://discord.com/invite/Jt5tfaM
I don't know the author but here is the reddit post:https://www.reddit.com/r/WebXR/comments/izvphc/ive_created_a_discord_server_for_webxr_it_has/

**Comment by Yonet** [comment]
title: Audio on the Web, for Games and VR!
url: https://medium.com/samsung-internet-dev/audio-on-the-web-for-games-and-vr-efcd523a3d58
author: Ada Rose Cannon
content: Audio is a fundamental way of adding important theming and immersion to games and virtual reality experiences on the Web. It’s not too hard to add but can do wonders for giving the user a wonderful experience.

**Comment by Yonet** [comment]
title: From Unity to Babylon.js — How is the journey?
url: https://babylonjs.medium.com/
author: Babylon.js
content: What is it like to move from a native engine like Unity to a WebGL engine like Babylon.js and WebXR?

**Comment by TrevorFSmith** [comment]
title: Introduction to WebXR with BabylonJS
url: https://www.meetup.com/hololens-mr/events/274042144/
author: @Yonet 
content: "In this talk, you will learn about WebXR Device APIs, why you would want to build with WebXR, current and future APIs, how to build and debug a BabylonJS applications. If you are considering to build your app with WebXR and wondering what is available and what is coming soon, join us to learn more."

**Comment by TrevorFSmith** [comment]
title: Personal identifiability of user tracking data during observation of 360-degree VR video
url: https://www.nature.com/articles/s41598-020-74486-y
author: Mark Roman Miller, Fernanda Herrera, Hanseul Jun, James A. Landay & Jeremy N. Bailenson
content: "Our work tests the identifiability of users under typical VR viewing circumstances, with no specially designed identifying task. Out of a pool of 511 participants, the system identifies 95% of users correctly when trained on less than 5 min of tracking data per person. We argue these results show nonverbal data should be understood by the public and by researchers as personally identifying data."

**Pull request merged**
